-- =====================================================================
-- healthcare_db: fixed lookup values (run after healthcare_db_schema.sql)
-- IDs are generated by AUTO_INCREMENT; data scripts look them up by label.
-- =====================================================================
USE healthcare_db;

INSERT INTO ResidenceType (Label, Description) VALUES
('Urban',    'County classified as urban (NCHS urban-rural codes 1-5).'),
('Suburban', 'Outside a central city but within a metropolitan area.'),
('Rural',    'County classified as rural / noncore (NCHS urban-rural code 6).');

INSERT INTO Gender (Label) VALUES
('Female'),
('Male'),
('Other');

INSERT INTO HealthLabel (CategoryLabelName, Description) VALUES
('Optimal',       'Low clinical risk, healthy biometrics, absence of chronic conditions, high subjective wellbeing.'),
('Moderate Risk', 'Mild risk factors, manageable chronic illness, or elevated lifestyle stress.'),
('High Burden',   'Multiple chronic conditions, severe lifestyle risk factors, or significant mental health strain.'),
('Critical Risk', 'Severe multi-morbidity requiring intensive medical intervention.');

-- BEA economic regions (codes as published in the BEA "Region" column)
INSERT INTO BEARegion (BEARegionCode, RegionName) VALUES
(1, 'New England'),
(2, 'Mideast'),
(3, 'Great Lakes'),
(4, 'Plains'),
(5, 'Southeast'),
(6, 'Southwest'),
(7, 'Rocky Mountain'),
(8, 'Far West');
